### ISSUE TITLE
Access of the annotated data at inception-gemtex-deid-base_project-grascco_raw

### ISSUE THREAD

**Issue by AbanoubAbdelmalak** [medizininformatik-initiative/GeMTeX#17]
Hello, 

I would like to ask how to read or visualize the annotation files ending with .ser .

Thank you.

**Comment by AbanoubAbdelmalak** [comment]
I have tried to import the project into [INCEpTION](https://inception-project.github.io/) but it did not respond and no error message was generated. 
I am using INCEPTION version 31.4. I have tried to import some of the test projects on [INCEPTION example page](https://inception-project.github.io/example-projects/) and it worked perfectly.

**Comment by reckart** [comment]
Do you have access to the logs?

**Comment by reckart** [comment]
Ok. I have made a test locally:

* downloaded the INCEpTION 31.4 JAR, started it up
* downloaded the `inception-gemtex-deid-base_project-grascco_raw.zip` file
* on the project overview page, clicked on *import project*, enabled *create missing users*, selected the ZIP file and imported
* after the import, I was redirected to the dashboard of the imported project

Maybe try downloading the ZIP from the repo again? Make sure to not extract/repackage it.

**Comment by AbanoubAbdelmalak** [comment]
Thank you for testing it. I am still looking at what could be wrong with my installation. 
Is there any scenarios where INCEpTION would not add events to the logs?

**Comment by reckart** [comment]
During a project import various messages should be logged by default (see your example from above).

If none of these are logged when you try importing the template, the process fails very early.

Maybe you can contact me by mail and we can look at your instance together.

**Comment by reckart** [comment]
Would you like to provide a PR to the INCEpTION Kubernetes tips with a warning about not being able to import projects if the ingress configuration is not allowing a proper payload size and an example of how to increase the payload size in the configuration?

https://github.com/inception-project/inception/blob/main/inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation_kubernetes.adoc

**Comment by AbanoubAbdelmalak** [comment]
> Would you like to provide a PR to the INCEpTION Kubernetes tips with a warning about not being able to import projects if the ingress configuration is not allowing a proper payload size and an example of how to increase the payload size in the configuration?
> 
> https://github.com/inception-project/inception/blob/main/inception/inception-doc/src/main/resources/META-INF/asciidoc/admin-guide/installation_kubernetes.adoc

Yes sure, Should I also add the setup of a MariaDB and how to connect to it by the INCEpTION service? 
I am a beginner at Kubernetes but I think it could be helpful to others and someone else with more experience can improve upon it.
