### ISSUE TITLE
[inception_ahd_recommender] use Github container registry for Docker image

### ISSUE THREAD

**Issue by AlexSchulz98** [medizininformatik-initiative/GeMTeX#25]
Für unsere K8s-Umgebung wäre es sehr praktisch, wenn wir das gebaute image für den Inception-AHD-Recommender direkt von Github pullen könnten. Momentan baue ich es noch selbst und hoste es intern bei uns im Harbor. Allerdings muss ich dabei alle Änderungen am Recommender händisch nachziehen, was auf Dauer keinen Sinn macht.

Ich hab mich mal durch die Github-Actions Doku gearbeitet und auf einem neuen Branch eine angepasste ci.yaml gepushed: 6ba80dcf3381328b96183a67e16aa15784ec1c5d

Können wir diesen Workflow hinzufügen?

Was dabei evtl noch wichtig wird, wären Releases. Nach den momentanen Einstellungen bastelt er sich selbst einen Tag aus Branch+Commit. Ich weiß allerdings nicht wie das später aussieht.

**Comment by fmatthies** [comment]
Ich habe mich noch nicht intensiv mit GitHub-Actions beschäftigt, aber könnte man das mit dem Tag so lösen: fa74d8bb0c325070f20003df1096c9f06bc458f8? Im Prinzip würde dann der Workflow nur getriggert wenn zusätzlich zum `push` auf `main` auch die `VERSION` Datei geändert wurde. - Zumindest ist das meine Intention.

**Comment by AlexSchulz98** [comment]
Hi,
erstmal sorry, ich wollte dir das nicht einfach so hinschmeißen, sondern nochmal testen, bin dann aber nicht mehr dazu gekommen...

Das mit der VERSION Datei find ich eine sehr gute Idee!

Ich kenn mich mit den Actions leider auch nicht so gut aus, habe mich aber mal etwas schlau gemacht und meine Erkenntnisse comitted: 00d079d (gerne korrigieren, falls das hier jemand mit mehr Ahnung liest):
- `tags:` braucht mehr als nur den tag. Deshalb reicht `tags: ${{ steps.verison.outputs.version }}` nicht. Ich hab es über die Envs gelöst mit:
 `tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}`.
- Der image-name muss wohl das Repo enthalten, damit es für ghcr funktioniert. Deshalb: 
`IMAGE_NAME: ${{ github.repository }}`
- image-names dürfen aber keine Großbuchstaben enthalten. Die meta-steps haben einen toLowercase Schritt inklusive. Bei unserer Lösung fehlt der noch, deshalb hab ich noch den Schritt `downcase IMAGE_NAME` ergänzt.

Hab es mit diesen Änderungen in einem privaten Repo erfolgreich getestet. Hast du noch Anmerkungen?

**Comment by fmatthies** [comment]
Habe das jetzt nicht getestet, sieht aber prinzipiell gut aus :) Einzig eine Frage: der generierte `tag` würde doch dann aber lauten:  
`ghcr.io/medizininformatik-initiative/gemtex:1.1.1`  
(`${{ github.repository }}` => `medizininformatik-initiative/gemtex`)

**Comment by AlexSchulz98** [comment]
Ja das dachte ich zuerst auch, habs hard-coded probiert und jedes mal einen Fehler "unauthorized" bekommen. Meine Vermutung ist, dass er `medizininformatik-initiative/gemtex` braucht, um es dem Repo zuzuordnen. Das image soll ja direkt im Repo gehostet werden und nur für das ist man auch mit dem `secrets.GITHUB_TOKEN` autorisiert.

`inception-ahd-recommender` zu ergänzen sollte aber kein Problem sein, habs mal ergänzt: a72b496
