### ISSUE TITLE
[inception_ahd_recommender] Dockerfile vereinfachen

### ISSUE THREAD

**Issue by fmatthies** [medizininformatik-initiative/GeMTeX#26]
I.M. wird in der Dockerfile bestimmt, wieviele Worker und welche Adresse für den Recommender benutzt werden. Das ist nicht ganz praktikabel:  
`RECOMMENDER_WORKER` und `RECOMMENDER_ADDRESS` Variablen aus dem Dockerfile extrahieren (und als `run` Argumente bzw. in die `docker-compose` überführen).

**Comment by reckart** [comment]
Braucht man wirklich eine Address? Ich denke normal sollte das insb. beim Docker betrieb einfach `0.0.0.0` sein.

**Comment by fmatthies** [comment]
Die Adresse ist prinzipiell auch eher um den Port zu konfigurieren. Ich würde die Möglichkeit der Konfiguration lassen; aber es gibt ja die Standardeinstellungen, die aufeinander abgestimmt sind.

**Comment by fmatthies** [comment]
Dockerfile sieht nun so aus
```
ARG ROOT_CONTAINER=python:3.7-slim
FROM $ROOT_CONTAINER

ARG RECOMMENDER_WORKDIR=/inception_ahd_recommender

WORKDIR $RECOMMENDER_WORKDIR

COPY . .

RUN python -m pip install --upgrade pip
RUN python -m pip install -e . &&\
    python -m pip install -e ".[contrib]"

ENTRYPOINT ["gunicorn"]
```

Dem `Entrypoint` können nun in der Form Argumente übergeben werden. Wenn der Container ohne Argumente gebaut wird, wird `gunicorn.conf.py` als Konfiguration benutzt (in der auch die `app` file angegeben ist):

```
import logging
import yaml

with open("docker-compose.yml") as stream:
    try:
        docker_yaml = yaml.safe_load(stream)
        env = {entry.split("=")[0].lower(): entry.split("=")[1]
               for entry in docker_yaml.get("services", {}).get("ahd-deid-recommender", {}).get("environment", [])}
    except yaml.YAMLError as err:
        logging.error(err)
        logging.error("Using default values for workers and address.")
        env = {}

workers = env.get("recommender_workers", 2)
bind = env.get("recommender_address", "127.0.0.1:8000")
log_level = 'info'
wsgi_app = "main:app"
```
