### ISSUE TITLE
[id-logik-recommender] session expires

### ISSUE THREAD

**Issue by fmatthies** [medizininformatik-initiative/GeMTeX#34]
Nach einiger Zeit (? Stunden) läuft die Session des IDLogik Servers ab. Dadurch ist der Service nicht mehr erreichbar. Zudem hat Recommender noch die alte `session id` gespeichtert und kann selbst bei Neustart des IDLogik Servers nicht mehr auf ihn zugreifen (`invalid session id`). Man muss den Recommender also auch neustarten.

1. Einfachste Lösung: Gibt es eine Einstellung, die verhindert, dass die Session des IDLogik Servers abläuft?
2. Wenn nicht: wie ist das Intervall? → dann müsste man den IDLogik Server Container entsprechend automatisch neustarten lassen.
3. Dafür müsste im Recommender der Code dahingehend geändert werden, dass eine neue `session id` angefordert wird, wenn die alte nicht mehr gültig ist
4. Wenn das nicht möglich ist: Recommender muss entsprechend Intervall aus (2) auch neugestartet werden

@fmeineke: zur Beobachtung

**Comment by zaus71** [comment]
Ich werde den 3. Vorschlag implementieren - das ist die robuste Lösung

**Comment by fmatthies** [comment]
Irgendwas funktioniert nicht ganz hier:  
`IdLogikServices:48` → `@Cacheable(value = "SCT_ANNO_CACHE", key = "#text", unless="#task.getResultItems().size()==0")`  
Ich bekomme ein  
`org.springframework.expression.spel.SpelEvaluationException: EL1011E: Method call: Attempted to call method getResultItems() on null context object`
Meine IDE sagt mir auch, dass die Variable 'task' (in der Annotation) nicht aufgelöst werden kann.

**Comment by fmatthies** [comment]
Hab doch schnell eine Lösung gefunden: "unless" wird erst ausgewertet nachdem die Methode durchgelaufen ist und man kann dann mit #result auf die Rückgabe referenzieren. Die Cache-Bedingung musste also lediglich modifiziert werden:  
`unless="#result.size()==0"`  
Scheint jetzt also soweit zu funktionieren; werde das Issue auflassen, bis wir sicher sind, dass auch das `expired session id` Problem gelöst ist.  

Danke für die schnelle Hilfe!

**Comment by fmatthies** [comment]
Sieht gut aus! In den Logs des IDLogik Servers haben sich über Nacht ein paar `Session with id '...' has expired`-Meldungen gesammelt.  Nach einer Probeannotation heute morgen bekomme ich in den Logs zwar zuerst einen `Invalid session id`, aber sofort danach ein `Login auf ... erfolgreich` und mir werden Vorschläge gemacht.
D.h. ich würde das issue schließen; danke nochmal!

**Comment by zaus71** [comment]
Super - Danke auch dir!
